### ISSUE TITLE
[Linux, GTK+2, bug] Fullscreen in Byuu does not scales properly 

### ISSUE THREAD

**Issue by MetalMaxMX** [higan-emu/higan#6] opened 2020-03-24 04:53 UTC
OS: Debian 10, 64 bits. Compiled under GCC. 

I have a slight issue. The interface and all have been working fine. However, When I map my hotkey to define fullscreen and then immediately go there, the screen does not scales up properly to that of my screen but rather it only takes a small pace. This issue does not happens in BSNES when I enter fullscreen. Is this a bug, intended behavior or is there anyway to fix this?

**Comment by Screwtapello** [comment] 2020-03-24 05:15
Does it work properly with the default GTK+2 UI?

**Comment by MetalMaxMX** [comment] 2020-03-24 05:57
After closer check-up, my mistake was that I confused the gtk and UI frontends due to a fork of BSNES using QT primarily (bsnes-plus). However, both bsnes (gtk) and bsnes-plus scale properly while Higan does not on GTK. I did not find any instructions on how to build Higan with QT enabled on the makefile so my sincere apologies for that. I did my due research and I couldn't find any docs explaining how to do that

**Comment by Screwtapello** [comment] 2020-04-11 08:10
Are you using byuu (shows a yellow "b" in the bottom-right before you start a game), or higan (black screen, with an interface panel at the bottom, before you start a game)?

Are you using the emulator's "switch to full-screen" key (which you probably have to set yourself) or your window manager/desktop environment's "toggle full-screen" key? What window manager or desktop environment are you using?

**Comment by Screwtapello** [comment] 2020-04-18 09:20
I've built higan and byuu from commit ed447c1, using the GTK+2 UI, and run them on Debian Testing with the i3 window manager. I tried using i3's "toggle fullscreen" hotkey (which I have bound to Win+U), and higan/byuu's own built-in "toggle fullscreen" hotkey (which I have bound to F11) and in both cases, for both emulators, the visual display was correctly scaled and centred on the screen.

**Comment by Screwtapello** [comment] 2020-04-18 09:40
I've also tried higan and byuu under XWayland inside GNOME 3. In this case, the window-manager's "toggle fullscreen" hotkey works, but higan/byuu's own "toggle fullscreen" hotkey creates a full-screen window but keeps drawing the video output at the same size and position, so it winds up near the top left corner.

**Comment by Screwtapello** [comment] 2020-04-18 10:03
If I build byuu with the GTK+3 UI, it breaks under Wayland because GTK+3 creates a native Wayland window but hiro tries to use X11 operations on it and fails.

If I set `GDK_BACKEND=x11` to force GTK+3 to create an X11 window, it's even worse than GTK+2 under XWayland - both the window-manager and built-in "toggle fullscreen" hotkeys cause the video to be drawn in the wrong place.

Originally, hiro was designed for GTK+2, and used low-level X11 calls for all the things that GTK+2 didn't provide an API for. hiro has a GTK+3 port, but it's really using GTK+3 in the same way it used GTK+2 - as a helper, with a lot of X11 calls sprinkled on top. Even though GTK+3 now has native APIs for a lot of the things GTK+2 was missing, hiro just re-uses the same X11 code for both, since it's simpler than trying to do different things for different GTK+ versions.

If there's some way to make the same code work for both X11 and XWayland, that would solve this issue. Otherwise, it's probably a matter of removing the optional GTK+3 parts of the hiro GTK backend, and creating a new GTK+3 backend from scratch. Or creating an entirely separate GTK+3 UI.

**Comment by jhlkek** [comment] 2020-06-07 18:38
I experience the same problem in KDE Plasma 5 under Xorg with both Qt 5 and GTK+ 2 GUIs. I'm pretty sure it has nothing to do with Wayland.

**Comment by Screwtapello** [comment] 2021-02-07 10:37
Closing this issue since the "byuu" UI has been removed from higan; it will continue as part of Near's "ares" project,

**Closed by Screwtapello** 2021-02-07 10:37 UTC
Labels: bug, help wanted
