### ISSUE TITLE
Qt5 GUI locks up

### ISSUE THREAD

**Issue by jhlkek** [higan-emu/higan#5] opened 2020-03-24 00:41 UTC
When launching byuu with Qt5 GUI for the first time, the program locks up and doesn't accept input. The GTK version does not lock up.

Higan with Qt5 GUI locks up if the user opens and closes the "About" dialog.

**Comment by btn21** [comment] 2020-03-30 11:44
Both icarus and higan segaults with libQt5Core:
icarus[34082]: segfault at 30 ip 00007f39a655f7d6 sp 00007ffda7919400 error 4 in libQt5Core.so.5.14.1[7f39a634a000+2f9000]
Code: 53 48 83 ec 28 8b 05 e1 34 29 00 83 f8 ff 7c 16 0f b6 05 7d 34 29 00 84 c0 0f 84 cd 00 00 00 4c 8d 35 8e 34 29 00 4d 8d 7e 30 <41> 8b 2f 41 89 ec 41 89 ed 41 81 e4 ff ff ff 00 41 81 e5 c0 ff ff

**Comment by Screwtapello** [comment] 2020-04-11 07:39
Although icarus and higan can be built against Qt5, that backend is not very well tested. If somebody has the time and expertise to figure out what's going and submit a patch, we'd love to receive a PR, but I for one won't be able to fix this myself.

If you just want to play games, I recommend the better-tested GTK2 or Win32 backends.

**Comment by baraclese** [comment] 2020-04-11 11:45
We had some patches for qt related errors recently. Modal dialogs are fixed in qt now. I can't reproduce the 'first launch' error that jhlkek describes. Could have been related to modal dialogs as well. btn21 needs to provide more info about what he does to trigger the segfault. I can tell that with the recent patches byuu hasn't shown any errors on my end with normal use, such as changing settings and playing games.

**Comment by Screwtapello** [comment] 2020-04-11 11:52
Ah, lovely, thanks for providing those fixes!

I'm going to close this issue now, but jhlkek - if you still have a problem, please leave a comment and I'll reopen it (or feel free to reopen it yourself, if that's a thing you can do)

**Closed by Screwtapello** 2020-04-11 11:52 UTC
Labels: bug, question
