### ISSUE TITLE
Inside the DSP firmware path, byuu expects folders named after each console, containing the actual firmware files

### ISSUE THREAD

**Issue by FitzRoyX** [higan-emu/higan#27] opened 2020-04-10 03:43 UTC
If you place your DSP files in the rom folder as per default path settings, byuu detects the files on rom load. But if you set a custom path via "Paths" and move your DSP files there, byuu will fail to detect the files.

![bb4](https://user-images.githubusercontent.com/57089001/78960095-9b825a00-7ab2-11ea-89aa-975a0c1268cd.png)

If we then navigate back to the path we specified, the files are indeed there. And so is a new folder that was apparently generated by that error message called "Super Famicom". If we now move the files into there, detection finally works.

![bb5](https://user-images.githubusercontent.com/57089001/78960367-77734880-7ab3-11ea-9fdd-069cb9a3064f.png)

**Comment by Screwtapello** [comment] 2020-04-11 11:35
It [looks like](https://github.com/higan-emu/higan/blob/309560b06073678bbe6f64e34ad6965ee68e995b/higan/target-byuu/emulator/emulator.cpp#L117-L119) this is a deliberate choice - byuu is a multi-system emulator, it specifically includes the system name (literally `interface->name()` in the linked code) in the path it searches for firmware files.

I'm going to mark this as a documentation bug, since the program is behaving as intended, it's just not immediately clear what it's intentions are.

**Comment by FitzRoyX** [comment] 2020-04-11 17:29
I'm kind of doubtful of that. BIOS files all have specific filepaths and this folder path specifically states "DSP Firmware". No other systems have DSP firmware, so I think it's inheriting the save file behavior of looking in separate folders without any reason to do so.

**Comment by Screwtapello** [comment] 2021-02-07 10:38
Closing this issue since the "byuu" UI has been removed from higan; it will continue as part of Near's "ares" project,

**Closed by Screwtapello** 2021-02-07 10:38 UTC
Labels: documentation
